### ISSUE TITLE
No module named 'encoding_model'

### ISSUE THREAD

**Issue by linzhl1** [chengsly/DeepMicroClass#10]
Hi,
I created a conda environment with python3.8 and installed the package using pip. When I downloaded the software and tested the predicted.py, it gave me the error as below:
**Traceback (most recent call last):
  File "/public1/group_lwj/software/DeepMicroClass/./predict.py", line 3, in <module>
    from tensorflow.keras.models import load_model
ModuleNotFoundError: No module named 'tensorflow'**
Then I installed tensorflow with command: 
`pip install tensorflow`
This time, another error raised up as below:
**2023-10-09 14:38:59.531822: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-09 14:38:59.837371: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-09 14:38:59.837440: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-09 14:38:59.839282: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-09 14:39:00.021074: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-09 14:39:00.022338: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-09 14:39:02.147113: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/public1/group_lwj/software/DeepMicroClass/./predict.py", line 4, in <module>
    from encoding_model import EncodingScheme
ModuleNotFoundError: No module named 'encoding_model'**
I find a similar issue #5 , but it does not work for me. Do you have any idea how to fix it?

**Comment by tianqitang1** [comment]
Please use the latest version of the package, it can be installed with ```pip install DeepMicroClass```.
