### ISSUE TITLE
Issues with the test run

### ISSUE THREAD

**Issue by dnolin13** [chengsly/DeepMicroClass#9]
getting this error for trying to run the test: 

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Step 2/3: Encode and predict...
Traceback (most recent call last):
  File "predict.py", line 203, in <module>
    score = predict_single(seq, options.modelLength)
  File "predict.py", line 146, in predict_single
    encodebw = encodingModel.encodeSeq(seqR)
  File "/home/delaney/software/DeepMicrobeFinder/encoding_model.py", line 67, in encodeSeq
    return self.encodeOneHotDNA(seq)
  File "/home/delaney/software/DeepMicrobeFinder/encoding_model.py", line 49, in encodeOneHotDNA
    return utils.seq2onehot(seq)[:, :4]
  File "/home/delaney/software/DeepMicrobeFinder/utils.py", line 53, in seq2onehot
    assert isinstance(seq, str), "Input should be str"
AssertionError: Input should be str

test code is

(dmf) ~/software/DeepMicrobeFinder$ python predict.py -i test.fasta -e one-hot -d models/one-hot-models/ -m single -l 1000

any help is appreciated, thanks!

**Comment by tianqitang1** [comment]
We have updated the software and please check the latest repo for it, thanks!
